// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8TfE2LLP94AvCChofXqJG-rw4hjm6zPA',
    appId: '1:696652473894:web:235a912a6dd7a4da3528e7',
    messagingSenderId: '696652473894',
    projectId: 'skunkworks-ai',
    authDomain: 'skunkworks-ai.firebaseapp.com',
    storageBucket: 'skunkworks-ai.appspot.com',
    measurementId: 'G-LK06XB0YR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSauhTHXtszIYIQSEUJcjilhokor-FStA',
    appId: '1:696652473894:android:31db5eac9912b3883528e7',
    messagingSenderId: '696652473894',
    projectId: 'skunkworks-ai',
    storageBucket: 'skunkworks-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcL6RgYP_X3n3t_gHkg8s5XGn9VDe1kLQ',
    appId: '1:696652473894:ios:66e17947aa3547463528e7',
    messagingSenderId: '696652473894',
    projectId: 'skunkworks-ai',
    storageBucket: 'skunkworks-ai.appspot.com',
    iosBundleId: 'com.boha.eduChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcL6RgYP_X3n3t_gHkg8s5XGn9VDe1kLQ',
    appId: '1:696652473894:ios:bbf48d95e3fa386b3528e7',
    messagingSenderId: '696652473894',
    projectId: 'skunkworks-ai',
    storageBucket: 'skunkworks-ai.appspot.com',
    iosBundleId: 'com.boha.eduChatbot.RunnerTests',
  );
}
